version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: deployments/docker/app.Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - configs/env/dev.env
    depends_on:
      - redis
      - postgres

  worker:
    build:
      context: .
      dockerfile: deployments/docker/worker.Dockerfile
    command: celery -A src.jobs.celery_config.app worker -Q analysis,training -P gevent
    env_file:
      - configs/env/dev.env
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: under_score
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: devpassword
    volumes:
      - pg_data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:v2.47
    ports:
      - "9090:9090"
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml

volumes:
  redis_data:
  pg_data:
