name: CI/CD Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: |
          pip install -r requirements.txt
          pytest -v --cov=src --cov-report=xml
      - uses: codecov/codecov-action@v3

  docker-build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: deployments/docker/app.Dockerfile
          tags: ghcr.io/under-score/api:latest
          push: ${{ github.ref == 'refs/heads/main' }}
